[package]
name = "rusty_combinion"
version = "0.1.0"
authors = ["Bastien JAUNY <bastien.jauny@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rusty_combinion"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["secrets"] }