[default.oauth.swcombine]
auth_uri = "https://www.swcombine.com/ws/oauth2/auth"
token_uri = "https://www.swcombine.com/ws/oauth2/token"
client_id = "..."
client_secret = "..."
redirect_uri = "http://localhost:8000/auth/swcombine"